document.write(''
+ '<!-- Casale Media 2005 (C) -->'
+ '<!-- Ad Format: Skyscraper -->'
+ '<!-- Domain(s): MeTeen.com -->'
+ '<scr' + 'ipt language="Javascript"><!--'
+ 'var d=new Date();var r=(d.getTime()%8673806982)+Math.random();var uu=escape(window.location.href);'
+ 'var wh=\'" width="120" height="600" \';var host=\'.casalemedia.com/\';var dc=document;'
+ 'var fr=\'marginwidth="0" hspace="0" vspace="0" frameborder="0" scrolling="no">\';'
+ 'dc.write(\'<ifr\'+\'ame src="http://as\'+host+\'s?s=62380&u=\'+uu+\'&f=3&id=\'+r+wh+fr);'
+ 'dc.write(\'<a hr\'+\'ef="http://c\'+host+\'c?s=62380&f=3&id=\'+r+\'" target="_blank">\');'
+ 'dc.write(\'<i\'+\'mg src="http://as\'+host+\'s?s=62380&u=\'+uu+\'&f=3&id=\'+r+\'&if=0\'+wh+\'border="0"></a></ifr\'+\'ame>\');'
+ '//--></scr' + 'ipt><nos ' + 'cript><iframe src="http://as.casalemedia.com/s?s=62380&u=http%3A%2F%2FMeTeen.com&f=3&id=1"'
+ 'width="120" height="600" marginwidth="0" hspace="0" vspace="0" frameborder="0" scrolling="no"><a'
+ 'href="http://c.casalemedia.com/c?s=62380&f=3&id=0" target="_blank"><img'
+ 'src="http://as.casalemedia.com/s?s=62380&u=http%3A%2F%2FMeTeen.com&f=3&id=0&if=0" width="120"'
+ 'height="600" border="0"></a></iframe></nos' + 'cript>'
+ '<!-- Casale Media 2005 (C) -->');